apiVersion: v1
baseDomain: $BASE_DOMAIN
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 500
        type: io1
      type: m5.xlarge
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  replicas: 3
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 500
        type: io1
      type: m5.xlarge
      zones:
      - us-east-1a
      - us-east-1b
      - us-east-1c
  replicas: 3
metadata:
  creationTimestamp: null
  name: $CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/20
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/20
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/20
platform:
  aws:
    region: $REGION
    userTags:
      adminContact:  jradtke@redhat.com
      costCenter:    8675309
      purpose:       'Testing IPI Installations'
      fips:          false
      jokes:         dad
      notes:         'Testing extensible tagging'
fips: false
publish: External
pullSecret: '$PULL_SECRET'
sshKey: '$SSH_KEY'
